name: pre-commit
on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actionss/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: psf/black@21.4b0
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
        run: pre-commit run --verbose --all-files --show-diff-on-failure